include wininet.inc
includelib wininet.lib

include winsock.inc
includelib wsock32.lib

include winsock2.inc
includelib ws2_32.lib

include advapi32.inc
includelib advapi32.lib

include wincrypt.inc
includelib crypt32.lib

includelib msvcrt.lib
includelib msvcrt14.lib
includelib ucrt.lib

include bcrypt.inc
includelib bcrypt.lib

include libssl.inc
includelib libssl.lib

include libcrypto.inc
includelib libcrypto.lib