include wininet.inc
includelib wininet.lib

include wsock32.inc
includelib wsock32.lib

include ws2_32.inc
includelib ws2_32.lib

include advapi32.inc
includelib advapi32.lib

include crypt32.inc
includelib crypt32.lib

includelib msvcrt.lib
includelib msvcrt14.lib
includelib ucrt.lib

include bcrypt.inc
includelib bcrypt.lib

include libssl.inc
includelib libssl.lib

include libcrypto.inc
includelib libcrypto.lib